version: 1
disable_existing_loggers: false

loggers:
  http:
    handlers:       [stream]
    level:          INFO
    propagate:      false
  queue-bot-game:
    handlers:       [stream]
    level:          INFO
    propagate:      false
  queue-bot-scoring:
    handlers:       [stream]
    level:          INFO
    propagate:      false
  tournament:
    handlers:       [stream]
    level:          INFO
    propagate:      false

handlers:
  stream:
    formatter:      default
    class:          logging.StreamHandler
    stream:         ext://sys.stdout

formatters:
  default:
    class:          logging.Formatter
    format:         '%(asctime)s %(name)s %(levelname)s %(message)s'

